################################################
#   Pipeline for COS_SCM                     #
################################################
name: COS_SCM
resources:
  containers:
  - container: mta
    image: 'devxci/mbtci:latest'
    options: --user 0:0
  - container: cfcli
    image: 'ppiper/cf-cli'
    options: --user 0:0 --privileged

trigger:
  - main

pool: 
    vmImage: 'ubuntu-latest'

################################
#   Build                      #
################################
stages:       
  - stage: build
    displayName: Build
    jobs:
      - job: build 
        container: mta
        steps: 
          - bash: 'mbt build -p=cf --mtar=COS_SCM.mtar'
          - publish: $(System.DefaultWorkingDirectory)/mta_archives/COS_SCM.mtar
            artifact: COS_SCM 

################################
#   Deploy DEV                 #
################################
  - stage: deploy_dev
    displayName: Deploy DEV
    dependsOn: build
    jobs:
      - deployment: build        
        environment: 'COS_SCM'
        container: cfcli
        strategy:
          runOnce:
            deploy:        
              steps:
               - download: current
                 artifact: COS_SCM
               - bash: 'cf login -u "$(CF-USER)" -p "$(CF-PASSWORD)" -a "$(CF-API)" -o "$(CF-ORG-DEV)" -s "$(CF-SPACE-DEV)"'
               - bash: 'cf deploy $(Pipeline.Workspace)/COS_SCM/COS_SCM.mtar -f'